language: csharp
dist: trusty
mono: none
dotnet: 2.0
solution: ThreeNumSum

install:
- dotnet restore ThreeNumSum
script:
- dotnet build ThreeNumSum
- dotnet test --logger "trx;LogFileName=temp.trx" ThreeNumSumTests
- ls ThreeNumSumTests
- cat ThreeNumSumTests/TestResults/temp.trx
